# Generated by Django 3.2.8 on 2021-10-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=500)),
                ('card_type', models.CharField(choices=[('land', 'Land'), ('creature', 'Creature'), ('enchantment', 'Enchantment'), ('artifact', 'Artifact'), ('instant', 'Instant'), ('sorcery', 'Sorcery')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
